In [1]:
import pandas as pd
from scipy.stats import gmean
from yfetch import get_stock_history
from symbols import my_etfs

risk_free_return = 0.04 # 4%

def crunch(history_weeks, weeks, symbols):
    assert history_weeks > weeks
    period = '5y' if history_weeks <= 262 else '10y'
    rows = []
    for symbol in symbols:
        history = get_stock_history(symbol, interval='1wk', period=period)
        history = history.tail(history_weeks)
        changes = history.Close.pct_change(periods=weeks).dropna()
        gmean_change = gmean(1 + changes) - 1 # geometric mean of changes
        std = changes.std()
        rows.append({
            'symbol': symbol,
            'weeks': len(history),
            'gmean': gmean_change,
            'std': std,
            'sharpe': (gmean_change - risk_free_return) / std,
        })
    
    df = pd.DataFrame(rows).sort_values(by='sharpe', ascending=False).reset_index(drop=True)
    for col in ['gmean', 'std']:
      df[col] = df[col].map('{:.2%}'.format)
    # display(df)
    return df

def crunch_etfs(history_weeks, weeks=52):
    df = crunch(history_weeks, weeks, my_etfs)
    f = f'data/stocks-{weeks}w-over-{history_weeks}w.csv'
    df.to_csv(f, index=False)
    print(f'Saved to {f} ({len(df)}/{len(my_etfs)})')
    return df

In [2]:
crunch_etfs(261, 52) # 1y over 5y

Saved to data/stocks-52w-over-261w.csv (25/25)

     symbol  weeks   gmean      std    sharpe
0   DFEN.DE    166  50.28%   12.74%  3.634086
1      NUKZ    123  59.70%   20.91%  2.663945
2      MAGS    164  38.04%   16.06%  2.120003
3   VDIV.DE    261  16.22%    6.97%  1.753741
4   EHF1.DE    261  11.11%    6.04%  1.178726
5       PPA    261  21.77%   15.44%  1.150768
6   ESIF.DE    261  20.83%   14.91%  1.128516
7      GC=F    261  22.41%   21.68%  0.849261
8   XLKS.MI    261  20.78%   22.69%  0.739467
9      SPMO    261  19.85%   23.23%  0.682523
10  JEDI.DE    206  40.64%   53.92%  0.679413
11     QTUM    261  22.40%   28.40%  0.647842
12      SMH    261  28.91%   40.24%  0.619073
13  CHIP.PA    261  29.18%   41.02%  0.613934
14     ROKT    261  21.41%   30.29%  0.574877
15      SPY    261  12.41%   14.90%  0.564742
16     FNGS    261  22.61%   34.56%  0.538480
17   SMH.MI    261  23.95%   37.45%  0.532693
18      IGM    261  17.82%   28.29%  0.488622
19      QQQ    261  14.55%   22.23%  0.474514
20      USD    261  53.65%  110.43%  0.449577
21  BTC-USD    261  20.71%   73.41%  0.227596
22      UFO    261  11.16%   49.09%  0.145924
23     BITQ    261   3.97%   71.37% -0.000364
24     DAPP    261   1.52%   78.24% -0.031722

In [3]:
crunch_etfs(156, 52) # 1y over 3y

Saved to data/stocks-52w-over-156w.csv (25/25)

     symbol  weeks   gmean     std    sharpe
0   ESIF.DE    156  32.61%   7.56%  3.784912
1   DFEN.DE    156  50.43%  13.25%  3.504087
2   VDIV.DE    156  19.90%   5.31%  2.991968
3   EHF1.DE    156  15.22%   3.94%  2.844593
4       PPA    156  33.46%  10.60%  2.778721
5      GC=F    156  41.98%  14.18%  2.678531
6      NUKZ    123  59.70%  20.91%  2.663945
7      QTUM    156  44.36%  17.91%  2.253488
8      SPMO    156  36.35%  14.92%  2.168932
9      FNGS    156  34.27%  14.36%  2.107327
10     MAGS    156  37.23%  16.35%  2.032044
11      QQQ    156  23.84%   9.81%  2.023014
12      SPY    156  20.80%   8.45%  1.987454
13      IGM    156  31.45%  14.52%  1.889893
14     BITQ    156  56.18%  39.51%  1.320625
15     ROKT    156  42.38%  29.93%  1.282421
16  JEDI.DE    156  66.33%  50.11%  1.244017
17  XLKS.MI    156  26.76%  18.69%  1.217865
18  CHIP.PA    156  45.86%  36.08%  1.160177
19      UFO    156  52.52%  42.50%  1.141611
20     DAPP    156  56.25%  45.84%  1.139944
21      SMH    156  43.91%  37.41%  1.066732
22      USD    156  91.69%  97.60%  0.898534
23  BTC-USD    156  50.60%  59.67%  0.781010
24   SMH.MI    156  32.95%  40.01%  0.723735

In [4]:
# High Sharpe picks
crunch(385, 52, ['VDIV.DE','LVHI','EHF1.DE'])

    symbol  weeks   gmean     std    sharpe
0  VDIV.DE    385  13.30%  14.20%  0.655134
1     LVHI    385  11.64%  13.01%  0.586954
2  EHF1.DE    385   9.25%  11.38%  0.461458

In [19]:
# Tech & AI picks
crunch(156, 52, ['MAGS','FNGS','SPMO','IGM','QQQ','BAI','WTAI','AGIX','CHAT','AIQ','BOTZ','IRBO','ROBO','THNQ','ARKQ','LRNZ','WISE'])

   symbol  weeks   gmean     std    sharpe
0    AGIX     98  36.49%  14.27%  2.276349
1    SPMO    156  36.35%  14.92%  2.168932
2    FNGS    156  34.27%  14.36%  2.107327
3     AIQ    156  28.30%  11.69%  2.078955
4    MAGS    156  37.23%  16.35%  2.032044
5     QQQ    156  23.84%   9.81%  2.023014
6     IGM    156  31.45%  14.52%  1.889893
7    THNQ    156  27.46%  14.80%  1.584923
8    ARKQ    156  44.10%  28.09%  1.427720
9     BAI     84  45.26%  28.93%  1.426294
10   CHAT    156  41.57%  31.19%  1.204466
11   WISE    130  23.28%  17.38%  1.109589
12   LRNZ    156  15.10%  12.38%  0.896575
13   WTAI    156  23.90%  24.65%  0.807605
14   IRBO    156  22.22%  24.05%  0.757573
15   BOTZ    156  12.95%  12.32%  0.726891
16   ROBO    156  12.94%  18.09%  0.494254

In [6]:
# Broad market picks
crunch(550, 52, ['SPY','SPYG','SPYV','SPMO','QQQ'])

  symbol  weeks   gmean     std    sharpe
0   SPMO    522  19.18%  17.95%  0.845427
1    QQQ    522  20.25%  19.95%  0.814771
2   SPYG    522  17.39%  17.24%  0.776911
3    SPY    522  14.74%  14.07%  0.763134
4   SPYV    522  11.18%  12.51%  0.573763

In [7]:
# Megacap picks
crunch(83, 52, ['SPY','QQQ','MAGS','FNGS','XLG','TOPT','QTOP','SPMO','IGM'])

  symbol  weeks   gmean     std    sharpe
0   SPMO     83  28.24%   9.44%  2.567724
1   TOPT     83  23.35%   7.74%  2.501194
2    XLG     83  22.08%   7.66%  2.360353
3    SPY     83  20.17%   7.00%  2.308561
4   MAGS     83  28.41%  11.04%  2.210973
5   QTOP     83  29.05%  11.71%  2.139801
6    QQQ     83  25.78%  10.26%  2.123435
7    IGM     83  33.42%  14.49%  2.030481
8   FNGS     83  22.49%  10.76%  1.718055

In [8]:
# Semiconductor picks
crunch(156, 52, ['SMH','USD','NVDA','AVGO','SOXX','PSI','SMH.MI','CHIP.PA','SEC0.DE'])

    symbol  weeks   gmean     std    sharpe
0     AVGO    156  81.29%  27.08%  2.854157
1  CHIP.PA    156  45.86%  36.08%  1.160177
2     NVDA    156  78.16%  68.29%  1.085836
3      SMH    156  43.91%  37.41%  1.066732
4      USD    156  91.69%  97.60%  0.898534
5   SMH.MI    156  32.95%  40.01%  0.723735
6     SOXX    156  30.06%  43.00%  0.605972
7  SEC0.DE    156  29.99%  45.18%  0.575325
8      PSI    156  31.16%  51.29%  0.529535

In [9]:
# Space picks
crunch(156, 52, ['UFO','ROKT','JEDI.DE'])

    symbol  weeks   gmean     std    sharpe
0     ROKT    156  42.38%  29.93%  1.282421
1  JEDI.DE    156  66.33%  50.11%  1.244017
2      UFO    156  52.52%  42.50%  1.141611

In [10]:
# Quantum picks
crunch(34, 26, ['QTUM','WQTM'])

  symbol  weeks   gmean     std    sharpe
0   QTUM     34  28.34%  15.26%  1.595226
1   WQTM     34  20.90%  23.18%  0.729235

In [11]:
# Power picks
crunch(45, 26, ['NUKZ','NLR','AIPO'])

  symbol  weeks   gmean     std    sharpe
0   AIPO     45  24.70%  11.00%  1.881394
1   NUKZ     45  10.92%   8.70%  0.795399
2    NLR     45  10.26%  14.24%  0.439590

In [12]:
# Defense picks
crunch(88, 52, ['ITA','PPA','XAR','4MMR.DE','DFEN.DE'])

    symbol  weeks   gmean     std    sharpe
0      XAR     88  53.44%  12.72%  3.886608
1      ITA     88  45.24%  10.76%  3.832554
2      PPA     88  39.65%  10.88%  3.276268
3  DFEN.DE     88  47.67%  16.38%  2.666258
4  4MMR.DE     88  52.35%  19.52%  2.476610

In [13]:
# Crypto picks
crunch(158, 52, ['DAPP','BITQ','BTC-USD'])

    symbol  weeks   gmean     std    sharpe
0     BITQ    158  56.59%  39.25%  1.340053
1     DAPP    158  56.71%  45.51%  1.158393
2  BTC-USD    158  52.01%  60.20%  0.797520

In [14]:
# Financial picks
crunch(156, 52, ['EXV1.DE','ESIF.DE'])

    symbol  weeks   gmean     std    sharpe
0  ESIF.DE    156  32.61%   7.56%  3.784912
1  EXV1.DE    156  46.56%  14.10%  3.017952

In [15]:
# Gold
crunch(522, 52, ['GC=F','GLDM','IAUM','SGOL','BAR','AAAU','IAU','OUNZ','GLD','FGDL',
                 '4GLD.DE','GLDA.DE','PPFB.DE','8PSG.DE','XGDU.DE','PHAU.L',
                 'EURUSD=X'])

      symbol  weeks   gmean     std    sharpe
0       FGDL    205  31.80%  18.29%  1.519825
1    PPFB.DE    255  21.75%  16.34%  1.086047
2       IAUM    257  22.78%  21.71%  0.865077
3    GLDA.DE    358  16.51%  16.47%  0.759710
4       GLDM    414  18.42%  19.21%  0.750751
5       AAAU    407  18.42%  19.36%  0.744821
6    XGDU.DE    319  16.91%  17.66%  0.731505
7        BAR    457  15.89%  19.50%  0.609922
8    4GLD.DE    522  13.20%  16.61%  0.554135
9       GC=F    522  14.07%  18.96%  0.531187
10      SGOL    522  13.81%  19.01%  0.515796
11       IAU    522  13.77%  18.97%  0.515250
12      OUNZ    522  13.71%  18.98%  0.511433
13    PHAU.L    522  13.63%  18.92%  0.509137
14   8PSG.DE    522  13.04%  17.77%  0.508656
15       GLD    522  13.61%  18.94%  0.507178
16  EURUSD=X    522   0.77%   7.25% -0.446187