In [1]:
import pandas as pd
from scipy.stats import gmean
from yfetch import get_stock_history, get_stock_name
from symbols import my_etfs

risk_free_return = 0.04 # 4%

def crunch(history_weeks, weeks, symbols):
    assert history_weeks > weeks
    period = '5y' if history_weeks <= 262 else '10y'
    rows = []
    for symbol in symbols:
        history = get_stock_history(symbol, interval='1wk', period=period, cache_days=3)
        history = history.tail(history_weeks)
        changes = history.Close.pct_change(periods=weeks, fill_method=None).dropna()
        gmean_change = gmean(1 + changes) - 1 # geometric mean of changes
        std = changes.std()
        rows.append({
            'symbol': symbol,
            'name': get_stock_name(symbol),
            'weeks': len(history),
            'gmean': gmean_change,
            'std': std,
            'sharpe': (gmean_change - risk_free_return) / std,
        })
    
    df = pd.DataFrame(rows).sort_values(by='sharpe', ascending=False).reset_index(drop=True)
    for col in ['gmean', 'std']:
      df[col] = df[col].map('{:.2%}'.format)
    # display(df)
    return df

def crunch_etfs(history_weeks, weeks=52):
    df = crunch(history_weeks, weeks, my_etfs + ['BRK-B'])
    f = f'data/stocks-{weeks}w-over-{history_weeks}w.csv'
    df.to_csv(f, index=False)
    print(f'Saved to {f} ({len(df)}/{len(my_etfs)})')
    return df

In [2]:
crunch_etfs(261, 52) # 1y over 5y

Saved to data/stocks-52w-over-261w.csv (20/19)

,symbol,name,weeks,gmean,std,sharpe
0,NUKZ,Range Nuclear Renaissance ETF,132,54.54%,23.93%,2.112137
1,MAGS,Roundhill Magnificent Seven ETF,173,36.59%,16.32%,1.996817
2,VDIV.DE,VanEck Morningstar Developed Markets Dividend ...,261,16.55%,7.40%,1.695754
3,ESIF.DE,iShares MSCI Europe Financials Sector UCITS ETF,261,22.41%,14.18%,1.297934
4,4GLD.DE,Xetra-Gold,261,22.20%,16.09%,1.130777
5,GC=F,Gold Aug 26,261,23.60%,20.98%,0.934250
6,XDWI.DE,Xtrackers MSCI World Industrials UCITS ETF 1C,261,13.23%,10.53%,0.876964
7,SPMO,Invesco S&P 500 Momentum ETF,261,21.90%,22.50%,0.795423
8,QTUM,Defiance Quantum ETF,261,25.90%,28.64%,0.764669
9,JEDI.DE,VanEck Space Innovators UCITS ETF,215,43.35%,54.61%,0.720541
10,SMH,VanEck Semiconductor ETF,261,34.07%,42.28%,0.711294
11,SPY,State Street SPDR S&P 500 ETF Trust,261,13.78%,14.28%,0.684596
12,BRK-B,Berkshire Hathaway Inc.,261,12.98%,13.24%,0.677835
13,FNGS,MicroSectors FANG+ ETN,261,25.08%,32.65%,0.645536
14,IGM,iShares Expanded Tech Sector ETF,261,20.93%,26.98%,0.627636
15,QQQ,Invesco QQQ Trust,261,16.74%,21.25%,0.599588
16,SPYG,State Street SPDR Portfolio S&P 500 Growth ETF,261,15.00%,19.60%,0.561330
17,USD,ProShares Ultra Semiconductors,261,62.76%,108.45%,0.541817
18,IWMO.MI,iShares Edge MSCI World Momentum Factor UCITS ETF,261,12.13%,17.32%,0.469619
19,BTC-USD,Bitcoin USD,261,20.19%,73.70%,0.219674

In [3]:
crunch_etfs(156, 52) # 6m over 3y

Saved to data/stocks-52w-over-156w.csv (20/19)

,symbol,name,weeks,gmean,std,sharpe
0,ESIF.DE,iShares MSCI Europe Financials Sector UCITS ETF,156,33.19%,7.33%,3.981103
1,4GLD.DE,Xetra-Gold,156,36.94%,8.91%,3.695145
2,VDIV.DE,VanEck Morningstar Developed Markets Dividend ...,156,20.93%,5.84%,2.896813
3,GC=F,Gold Aug 26,156,42.18%,13.93%,2.741374
4,QTUM,Defiance Quantum ETF,156,48.22%,18.19%,2.430585
5,SPYG,State Street SPDR Portfolio S&P 500 Growth ETF,156,26.25%,9.66%,2.304564
6,SPMO,Invesco S&P 500 Momentum ETF,156,34.68%,13.61%,2.254078
7,NUKZ,Range Nuclear Renaissance ETF,132,54.54%,23.93%,2.112137
8,QQQ,Invesco QQQ Trust,156,23.91%,9.92%,2.007943
9,SPY,State Street SPDR S&P 500 ETF Trust,156,20.57%,8.40%,1.972536
10,IGM,iShares Expanded Tech Sector ETF,156,31.40%,14.55%,1.883664
11,FNGS,MicroSectors FANG+ ETN,156,31.74%,14.98%,1.852039
12,MAGS,Roundhill Magnificent Seven ETF,156,34.67%,16.69%,1.837442
13,JEDI.DE,VanEck Space Innovators UCITS ETF,156,77.05%,46.09%,1.584949
14,XDWI.DE,Xtrackers MSCI World Industrials UCITS ETF 1C,156,17.41%,8.88%,1.509570
15,IWMO.MI,iShares Edge MSCI World Momentum Factor UCITS ETF,156,19.72%,14.09%,1.115575
16,SMH,VanEck Semiconductor ETF,156,47.03%,42.09%,1.022269
17,USD,ProShares Ultra Semiconductors,156,88.01%,93.35%,0.899899
18,BRK-B,Berkshire Hathaway Inc.,156,13.08%,12.96%,0.700798
19,BTC-USD,Bitcoin USD,156,34.12%,63.20%,0.476627

In [4]:
# High Sharpe
crunch(262, 52, ['VDIV.DE','LVHI','EHF1.DE'])

,symbol,name,weeks,gmean,std,sharpe
0,VDIV.DE,VanEck Morningstar Developed Markets Dividend ...,261,16.55%,7.40%,1.695754
1,LVHI,Franklin International Low Volatility High Div...,261,16.69%,9.00%,1.409826
2,EHF1.DE,Amundi Index Solutions - Amundi MSCI Europe Hi...,261,11.66%,6.08%,1.259865

In [5]:
# Momentum
crunch(262, 52, ['SPMO','IWMO.MI','IMTM','EEMO'])

,symbol,name,weeks,gmean,std,sharpe
0,SPMO,Invesco S&P 500 Momentum ETF,261,21.90%,22.50%,0.795423
1,IMTM,iShares MSCI Intl Momentum Factor ETF,261,12.13%,15.62%,0.520708
2,IWMO.MI,iShares Edge MSCI World Momentum Factor UCITS ETF,261,12.13%,17.32%,0.469619
3,EEMO,Invesco S&P Emerging Markets Momentum ETF,261,6.36%,17.68%,0.133238

In [6]:
# Broad market
crunch(156, 52, ['SPY','SPYM','SPYG','SPYV','SPMO','QQQ','IS3S.DE'])

,symbol,name,weeks,gmean,std,sharpe
0,SPYG,State Street SPDR Portfolio S&P 500 Growth ETF,156,26.25%,9.66%,2.304564
1,SPMO,Invesco S&P 500 Momentum ETF,156,34.68%,13.61%,2.254078
2,QQQ,Invesco QQQ Trust,156,23.91%,9.92%,2.007943
3,SPYM,State Street SPDR Portfolio S&P 500 ETF,156,20.67%,8.41%,1.981124
4,SPY,State Street SPDR S&P 500 ETF Trust,156,20.57%,8.40%,1.972536
5,SPYV,State Street SPDR Portfolio S&P 500 Value ETF,156,14.00%,8.47%,1.180608
6,IS3S.DE,iShares Edge MSCI World Value Factor UCITS ETF...,156,20.89%,17.30%,0.976164

In [7]:
# Megacap
crunch(93, 52, ['SPY','SPYM','SPYG','QQQ','MAGS','FNGS','XLG','MGK','TOPT','QTOP','SPMO','IGM'])

,symbol,name,weeks,gmean,std,sharpe
0,SPMO,Invesco S&P 500 Momentum ETF,93,30.06%,9.51%,2.740566
1,SPYG,State Street SPDR Portfolio S&P 500 Growth ETF,93,24.95%,7.77%,2.697757
2,TOPT,iShares Top 20 U.S. Stocks ETF,93,22.90%,7.07%,2.672916
3,SPYM,State Street SPDR Portfolio S&P 500 ETF,93,20.61%,6.29%,2.642558
4,SPY,State Street SPDR S&P 500 ETF Trust,93,20.53%,6.28%,2.631121
5,XLG,Invesco S&P 500 Top 50 ETF,93,21.26%,7.14%,2.416002
6,QTOP,iShares Nasdaq Top 30 Stocks ETF,93,29.90%,10.76%,2.407864
7,QQQ,Invesco QQQ Trust,93,26.72%,9.50%,2.390522
8,MGK,Vanguard Morningstar Mega Cap Growth ETF,93,21.97%,7.68%,2.339131
9,IGM,iShares Expanded Tech Sector ETF,93,35.24%,13.45%,2.322841
10,MAGS,Roundhill Magnificent Seven ETF,93,26.62%,10.68%,2.118862
11,FNGS,MicroSectors FANG+ ETN,93,21.32%,10.41%,1.663719

In [8]:
# Semiconductor
crunch(156, 52, ['SMH','USD','NVDA','AVGO','SOXX','PSI','SMH.MI','CHIP.PA','SEC0.DE'])

,symbol,name,weeks,gmean,std,sharpe
0,AVGO,Broadcom Inc.,156,77.11%,29.13%,2.509353
1,CHIP.PA,Amundi MSCI Semiconductors UCITS ETF Acc,156,47.81%,39.21%,1.117254
2,SMH,VanEck Semiconductor ETF,156,47.03%,42.09%,1.022269
3,NVDA,NVIDIA Corporation,156,66.49%,63.21%,0.988512
4,USD,ProShares Ultra Semiconductors,156,88.01%,93.35%,0.899899
5,SMH.MI,VanEck Semiconductor UCITS ETF,156,38.16%,50.51%,0.676441
6,SOXX,iShares Semiconductor ETF,156,35.93%,52.77%,0.605068
7,SEC0.DE,iShares MSCI Global Semiconductors UCITS ETF U...,156,36.79%,58.74%,0.558204
8,PSI,Invesco Semiconductors ETF,156,39.08%,63.12%,0.555813

In [9]:
# Space picks
crunch(156, 52, ['UFO','ROKT','JEDI.DE'])

,symbol,name,weeks,gmean,std,sharpe
0,JEDI.DE,VanEck Space Innovators UCITS ETF,156,77.05%,46.09%,1.584949
1,UFO,Procure Space ETF,156,61.49%,37.06%,1.551457
2,ROKT,State Street SPDR S&P Kensho Final Frontiers ETF,156,48.81%,28.90%,1.550388

In [10]:
# Quantum picks
crunch(34, 26, ['QTUM','WQTM'])

  symbol                               name  weeks   gmean     std    sharpe
0   QTUM               Defiance Quantum ETF     34  33.30%  12.63%  2.319631
1   WQTM  WisdomTree Quantum Computing Fund     34  25.39%  13.81%  1.549152

In [11]:
# Power picks
crunch(156, 52, ['NUKZ','NLR','AIPO'])

,symbol,name,weeks,gmean,std,sharpe
0,AIPO,Defiance AI & Power Infrastructure ETF,54,43.06%,1.47%,26.574707
1,NUKZ,Range Nuclear Renaissance ETF,132,54.54%,23.93%,2.112137
2,NLR,VanEck Uranium and Nuclear ETF,156,35.44%,27.91%,1.126177

In [12]:
# Defense picks
crunch(88, 52, ['ITA','PPA','XAR','4MMR.DE','DFEN.DE'])

,symbol,name,weeks,gmean,std,sharpe
0,XAR,State Street SPDR S&P Aerospace & Defense ETF,88,49.22%,16.11%,2.807051
1,ITA,iShares U.S. Aerospace & Defense ETF,88,41.94%,13.54%,2.802797
2,PPA,Invesco Aerospace & Defense ETF,88,37.56%,12.73%,2.635778
3,DFEN.DE,VanEck Defense ETF A USD Acc,88,34.32%,21.82%,1.389431
4,4MMR.DE,Global X Defence Tech UCITS ETF USD Accumulating,88,36.32%,25.17%,1.284340

In [13]:
# Crypto picks
crunch(158, 52, ['DAPP','BITQ','BTC-USD'])

,symbol,name,weeks,gmean,std,sharpe
0,BITQ,Bitwise Crypto Industry Innovators ETF,158,52.39%,40.04%,1.208538
1,DAPP,VanEck Digital Transformation ETF,158,51.16%,46.80%,1.007653
2,BTC-USD,Bitcoin USD,158,35.33%,63.32%,0.494874

In [14]:
# Financial picks
crunch(262, 52, ['EXV1.DE','ESIF.DE'])

,symbol,name,weeks,gmean,std,sharpe
0,EXV1.DE,iShares STOXX Europe 600 Banks UCITS ETF (DE),261,32.38%,20.60%,1.377998
1,ESIF.DE,iShares MSCI Europe Financials Sector UCITS ETF,261,22.41%,14.18%,1.297934

In [15]:
# Gold
crunch(262, 52, ['GC=F','GLDM','IAUM','SGOL','BAR','AAAU','IAU','OUNZ','GLD','FGDL',
                 '4GLD.DE','GLDA.DE','PPFB.DE','8PSG.DE','XGDU.DE','PHAU.L',
                 'EURUSD=X'])

,symbol,name,weeks,gmean,std,sharpe
0,FGDL,Franklin Responsibly Sourced Gold ETF,214,31.30%,17.93%,1.522642
1,4GLD.DE,Xetra-Gold,261,22.20%,16.09%,1.130777
2,GLDA.DE,Amundi Physical Metals PLC E,261,22.05%,16.05%,1.124566
3,PPFB.DE,iShares Physical Metals PLC O,261,22.05%,16.06%,1.124169
4,XGDU.DE,XTrackers ETC PLC E,261,22.14%,16.24%,1.117305
5,8PSG.DE,Invesco Physical Markets PLC O,261,22.13%,18.45%,0.982678
6,GC=F,Gold Aug 26,261,23.60%,20.98%,0.934250
7,IAUM,iShares Gold Trust Micro,261,23.51%,21.06%,0.926126
8,GLDM,SPDR Gold MiniShares,261,23.47%,21.06%,0.924450
9,SGOL,abrdn Physical Gold Shares ETF,261,23.38%,21.04%,0.921149
10,AAAU,Goldman Sachs Physical Gold ETF,261,23.37%,21.04%,0.920589
11,BAR,GraniteShares Gold Trust,261,23.37%,21.05%,0.920266
12,OUNZ,VanEck Merk Gold Trust,261,23.28%,21.02%,0.917194
13,IAU,iShares Gold Trust,261,23.28%,21.03%,0.916838
14,PHAU.L,WisdomTree Physical Gold,261,23.14%,20.99%,0.911893
15,GLD,SPDR Gold Shares,261,23.11%,21.01%,0.909465
16,EURUSD=X,EUR/USD,262,1.09%,6.83%,-0.426255

In [16]:
# Precious metals
crunch(262, 52, ['PHPM.MI'])

,symbol,name,weeks,gmean,std,sharpe
0,PHPM.MI,WisdomTree Physical Precious Metals,261,15.74%,24.11%,0.486779

In [17]:
# Materials & Industrials
crunch(262, 52, ['XDWI.DE','WIND.AS','EXI','WMIN.DE','PICK','XDWM.DE','COPX','URNM'])

,symbol,name,weeks,gmean,std,sharpe
0,XDWI.DE,Xtrackers MSCI World Industrials UCITS ETF 1C,261,13.23%,10.53%,0.876964
1,WIND.AS,State Street SPDR MSCI World Industrials UCITS...,261,13.17%,10.55%,0.868762
2,EXI,iShares Global Industrials ETF,261,14.42%,13.91%,0.749089
3,COPX,Global X Copper Miners ETF,261,20.18%,40.18%,0.402665
4,WMIN.DE,VanEck S&P Global Mining UCITS ETF,261,15.09%,29.66%,0.373974
5,URNM,Sprott Uranium Miners ETF,261,15.85%,38.17%,0.310551
6,PICK,iShares MSCI Global Metals & Mining Producers ETF,261,9.88%,26.68%,0.220449
7,XDWM.DE,Xtrackers MSCI World Materials UCITS ETF 1C,261,6.15%,10.77%,0.199488

In [18]:
# Tech & AI picks
crunch(156, 52, ['MAGS','FNGS','SPMO','IGM','QQQ','BAI','WTAI','AGIX','CHAT','AIQ','BOTZ','ROBO','THNQ','ARKQ','LRNZ','WISE'])

,symbol,name,weeks,gmean,std,sharpe
0,AGIX,KraneShares Artificial Intelligence and Techno...,107,37.71%,13.80%,2.443138
1,SPMO,Invesco S&P 500 Momentum ETF,156,34.68%,13.61%,2.254078
2,AIQ,Global X Artificial Intelligence & Technology ETF,156,29.86%,12.61%,2.050646
3,QQQ,Invesco QQQ Trust,156,23.91%,9.92%,2.007943
4,IGM,iShares Expanded Tech Sector ETF,156,31.40%,14.55%,1.883664
5,FNGS,MicroSectors FANG+ ETN,156,31.74%,14.98%,1.852039
6,MAGS,Roundhill Magnificent Seven ETF,156,34.67%,16.69%,1.837442
7,ARKQ,ARK Autonomous Technology & Robotics ETF,156,48.25%,24.73%,1.789542
8,BAI,iShares A.I. Innovation and Tech Active ETF,93,49.39%,28.12%,1.614035
9,THNQ,Robo Global Artificial Intelligence ETF,156,30.45%,17.16%,1.541073
10,CHAT,Roundhill Generative AI & Technology ETF,156,46.98%,33.86%,1.269590
11,WISE,Themes Generative Artificial Intelligence ETF,139,21.54%,17.70%,0.990972
12,LRNZ,"TrueShares Technology, AI and Deep Learning ETF",156,16.47%,13.75%,0.906800
13,WTAI,WisdomTree Artificial Intelligence and Innovat...,156,29.56%,28.41%,0.899673
14,BOTZ,Global X Robotics & Artificial Intelligence ETF,156,13.43%,12.42%,0.759096
15,ROBO,Robo Global Robotics and Automation Index ETF,156,16.56%,18.40%,0.682309