In [1]:
import pandas as pd
from scipy.stats import gmean
from yfetch import get_stock_history, get_stock_name
from symbols import my_etfs

risk_free_return = 0.04 # 4%

def crunch(history_weeks, weeks, symbols):
    assert history_weeks > weeks
    period = '5y' if history_weeks <= 262 else '10y'
    rows = []
    for symbol in symbols:
        history = get_stock_history(symbol, interval='1wk', period=period, cache_days=3)
        history = history.tail(history_weeks)
        changes = history.Close.pct_change(periods=weeks, fill_method=None).dropna()
        gmean_change = gmean(1 + changes) - 1 # geometric mean of changes
        std = changes.std()
        rows.append({
            'symbol': symbol,
            'name': get_stock_name(symbol),
            'weeks': len(history),
            'gmean': gmean_change,
            'std': std,
            'sharpe': (gmean_change - risk_free_return) / std,
        })
    
    df = pd.DataFrame(rows).sort_values(by='sharpe', ascending=False).reset_index(drop=True)
    for col in ['gmean', 'std']:
      df[col] = df[col].map('{:.2%}'.format)
    # display(df)
    return df

def crunch_etfs(history_weeks, weeks=52):
    df = crunch(history_weeks, weeks, my_etfs + ['BRK-B'])
    f = f'data/stocks-{weeks}w-over-{history_weeks}w.csv'
    df.to_csv(f, index=False)
    print(f'Saved to {f} ({len(df)}/{len(my_etfs)})')
    return df

In [2]:
crunch_etfs(261, 52) # 1y over 5y

Fetched history for SPY (261 weeks)
Fetched history for VDIV.DE (261 weeks)
Fetched history for BTC-USD (261 weeks)
Fetched history for GC=F (261 weeks)
Saved to data/stocks-52w-over-261w.csv (23/22)

,symbol,name,weeks,gmean,std,sharpe
0,NUKZ,Range Nuclear Renaissance ETF,134,53.43%,24.49%,2.018334
1,MAGS,Roundhill Magnificent Seven ETF,175,36.22%,16.42%,1.962294
2,VDIV.DE,VanEck Morningstar Developed Markets Dividend ...,261,16.64%,7.50%,1.683929
3,PPA,Invesco Aerospace & Defense ETF,261,23.45%,14.04%,1.385361
4,ESIF.DE,iShares MSCI Europe Financials Sector UCITS ETF,261,22.75%,14.00%,1.338957
5,4GLD.DE,Xetra-Gold,261,22.34%,16.10%,1.138940
6,GC=F,Gold Dec 26,261,23.89%,20.85%,0.953751
7,XDWI.DE,Xtrackers MSCI World Industrials UCITS ETF 1C,261,13.45%,10.50%,0.900072
8,SPMO,Invesco S&P 500 Momentum ETF,261,22.29%,22.30%,0.820516
9,QTUM,Defiance Quantum ETF,261,26.65%,28.65%,0.790518
10,SMH,VanEck Semiconductor ETF,261,35.06%,42.39%,0.732640
11,JEDI.DE,VanEck Space Innovators UCITS ETF,217,43.79%,54.39%,0.731517
12,SPY,State Street SPDR S&P 500 ETF Trust,261,14.04%,14.18%,0.708218
13,BRK-B,Berkshire Hathaway Inc.,261,13.03%,13.22%,0.683297
14,FNGS,MicroSectors FANG+ ETN,261,25.59%,32.28%,0.668823
15,IGM,iShares Expanded Tech Sector ETF,261,21.53%,26.71%,0.656382
16,QQQ,Invesco QQQ Trust,261,17.14%,21.06%,0.623917
17,SPYG,State Street SPDR Portfolio S&P 500 Growth ETF,261,15.33%,19.46%,0.582113
18,USD,ProShares Ultra Semiconductors,261,64.38%,107.76%,0.560349
19,IWMO.MI,iShares Edge MSCI World Momentum Factor UCITS ETF,261,12.46%,17.27%,0.489803
20,BTC-USD,Bitcoin USD,261,20.23%,73.68%,0.220316
21,BITQ,Bitwise Crypto Industry Innovators ETF,261,11.42%,67.81%,0.109413
22,DAPP,VanEck Digital Transformation ETF,261,9.64%,74.39%,0.075784

In [3]:
crunch_etfs(156, 52) # 6m over 3y

Saved to data/stocks-52w-over-156w.csv (23/22)

,symbol,name,weeks,gmean,std,sharpe
0,ESIF.DE,iShares MSCI Europe Financials Sector UCITS ETF,156,33.36%,7.18%,4.085740
1,4GLD.DE,Xetra-Gold,156,36.99%,8.87%,3.717684
2,VDIV.DE,VanEck Morningstar Developed Markets Dividend ...,156,21.18%,5.93%,2.897120
3,GC=F,Gold Dec 26,156,42.16%,13.96%,2.733399
4,PPA,Invesco Aerospace & Defense ETF,156,33.23%,10.82%,2.701780
5,QTUM,Defiance Quantum ETF,156,49.12%,18.00%,2.507159
6,SPYG,State Street SPDR Portfolio S&P 500 Growth ETF,156,26.13%,9.63%,2.298712
7,SPMO,Invesco S&P 500 Momentum ETF,156,34.34%,13.48%,2.250923
8,NUKZ,Range Nuclear Renaissance ETF,134,53.43%,24.49%,2.018334
9,QQQ,Invesco QQQ Trust,156,23.88%,9.88%,2.011875
10,SPY,State Street SPDR S&P 500 ETF Trust,156,20.53%,8.37%,1.974626
11,IGM,iShares Expanded Tech Sector ETF,156,31.36%,14.50%,1.886557
12,FNGS,MicroSectors FANG+ ETN,156,31.25%,14.90%,1.829384
13,MAGS,Roundhill Magnificent Seven ETF,156,34.07%,16.82%,1.787517
14,JEDI.DE,VanEck Space Innovators UCITS ETF,156,78.97%,44.80%,1.673659
15,XDWI.DE,Xtrackers MSCI World Industrials UCITS ETF 1C,156,17.51%,8.92%,1.515370
16,BITQ,Bitwise Crypto Industry Innovators ETF,156,51.70%,40.72%,1.171255
17,IWMO.MI,iShares Edge MSCI World Momentum Factor UCITS ETF,156,19.61%,13.99%,1.115861
18,SMH,VanEck Semiconductor ETF,156,47.61%,42.55%,1.024927
19,DAPP,VanEck Digital Transformation ETF,156,50.02%,47.75%,0.963776
20,USD,ProShares Ultra Semiconductors,156,86.93%,92.60%,0.895605
21,BRK-B,Berkshire Hathaway Inc.,156,12.81%,12.91%,0.682560
22,BTC-USD,Bitcoin USD,156,30.66%,63.87%,0.417387

In [6]:
# High Sharpe
crunch(156, 52, ['VDIV.DE','LVHI','EHF1.DE','EFAS'])

Fetched history for EFAS (262 weeks)

,symbol,name,weeks,gmean,std,sharpe
0,VDIV.DE,VanEck Morningstar Developed Markets Dividend ...,156,21.37%,6.01%,2.887986
1,EHF1.DE,Amundi Index Solutions - Amundi MSCI Europe Hi...,156,15.45%,4.07%,2.813082
2,LVHI,Franklin International Low Volatility High Div...,156,22.74%,7.86%,2.384510
3,EFAS,Global X MSCI SuperDividend EAFE ETF,156,27.76%,12.12%,1.961553

In [5]:
# Momentum
crunch(156, 52, ['SPMO','IWMO.MI','IMTM','EEMO','IDMO'])

,symbol,name,weeks,gmean,std,sharpe
0,IDMO,Invesco S&P International Developed Momentum ETF,156,25.69%,9.29%,2.335626
1,SPMO,Invesco S&P 500 Momentum ETF,156,34.09%,13.32%,2.257945
2,IMTM,iShares MSCI Intl Momentum Factor ETF,156,22.05%,8.52%,2.116860
3,IWMO.MI,iShares Edge MSCI World Momentum Factor UCITS ETF,156,19.52%,13.91%,1.115519
4,EEMO,Invesco S&P Emerging Markets Momentum ETF,156,14.01%,15.34%,0.653005

In [6]:
# Broad market
crunch(156, 52, ['SPY','SPYM','SPYG','SPYV','SPMO','QQQ','IS3S.DE','TQQQ'])

Fetched history for SPYM (261 weeks)
Fetched history for SPYV (261 weeks)
Fetched history for IS3S.DE (261 weeks)
Fetched history for TQQQ (261 weeks)

,symbol,name,weeks,gmean,std,sharpe
0,SPYG,State Street SPDR Portfolio S&P 500 Growth ETF,156,26.13%,9.63%,2.298712
1,SPMO,Invesco S&P 500 Momentum ETF,156,34.34%,13.48%,2.250923
2,QQQ,Invesco QQQ Trust,156,23.88%,9.88%,2.011875
3,SPYM,State Street SPDR Portfolio S&P 500 ETF,156,20.62%,8.38%,1.983182
4,SPY,State Street SPDR S&P 500 ETF Trust,156,20.53%,8.37%,1.974626
5,SPYV,State Street SPDR Portfolio S&P 500 Value ETF,156,14.03%,8.48%,1.182604
6,TQQQ,ProShares UltraPro QQQ,156,48.37%,41.43%,1.071142
7,IS3S.DE,iShares Edge MSCI World Value Factor UCITS ETF...,156,21.71%,17.90%,0.989461

In [8]:
# Megacap
crunch(156, 52, ['SPY','SPYM','SPYG','QQQ','MAGS','FNGS','XLG','MGK','TOPT','QTOP','SPMO','IGM','WLDR'])

,symbol,name,weeks,gmean,std,sharpe
0,TOPT,iShares Top 20 U.S. Stocks ETF,97,22.36%,6.98%,2.630013
1,QTOP,iShares Nasdaq Top 30 Stocks ETF,97,29.53%,10.34%,2.469084
2,SPYG,State Street SPDR Portfolio S&P 500 Growth ETF,156,26.00%,9.60%,2.290964
3,SPMO,Invesco S&P 500 Momentum ETF,156,34.09%,13.32%,2.257945
4,QQQ,Invesco QQQ Trust,156,23.81%,9.84%,2.012116
5,SPYM,State Street SPDR Portfolio S&P 500 ETF,156,20.47%,8.32%,1.980427
6,SPY,State Street SPDR S&P 500 ETF Trust,156,20.37%,8.30%,1.971936
7,MGK,Vanguard Morningstar Mega Cap Growth ETF,156,23.39%,9.88%,1.961513
8,IGM,iShares Expanded Tech Sector ETF,156,31.28%,14.45%,1.887913
9,XLG,Invesco S&P 500 Top 50 ETF,156,22.25%,9.76%,1.870479
10,FNGS,MicroSectors FANG+ ETN,156,30.98%,14.85%,1.817407
11,WLDR,Affinity World Leaders Equity ETF,156,29.79%,14.42%,1.788610
12,MAGS,Roundhill Magnificent Seven ETF,156,33.70%,16.86%,1.761421

In [8]:
# Semiconductor
crunch(156, 52, ['SMH','USD','NVDA','AVGO','SOXX','PSI','SMH.MI','CHIP.PA','SEC0.DE'])

Fetched history for SOXX (261 weeks)
Fetched history for PSI (261 weeks)
Fetched history for SMH.MI (261 weeks)
Fetched history for CHIP.PA (261 weeks)
Fetched history for SEC0.DE (261 weeks)

,symbol,name,weeks,gmean,std,sharpe
0,AVGO,Broadcom Inc.,156,75.90%,29.67%,2.423473
1,CHIP.PA,Amundi MSCI Semiconductors UCITS ETF Acc,156,48.12%,39.47%,1.117762
2,SMH,VanEck Semiconductor ETF,156,47.61%,42.55%,1.024927
3,NVDA,NVIDIA Corporation,156,63.99%,62.09%,0.966157
4,USD,ProShares Ultra Semiconductors,156,86.93%,92.60%,0.895605
5,SMH.MI,VanEck Semiconductor UCITS ETF,156,39.25%,51.62%,0.682826
6,SOXX,iShares Semiconductor ETF,156,37.19%,53.88%,0.615973
7,PSI,Invesco Semiconductors ETF,156,40.89%,64.49%,0.572056
8,SEC0.DE,iShares MSCI Global Semiconductors UCITS ETF U...,156,38.24%,60.17%,0.568999

In [9]:
# Space picks
crunch(156, 52, ['UFO','ROKT','JEDI.DE'])

,symbol,name,weeks,gmean,std,sharpe
0,JEDI.DE,VanEck Space Innovators UCITS ETF,156,78.97%,44.80%,1.673659
1,UFO,Procure Space ETF,156,63.08%,35.75%,1.652389
2,ROKT,State Street SPDR S&P Kensho Final Frontiers ETF,156,50.06%,28.61%,1.609918

In [10]:
# Quantum picks
crunch(34, 26, ['QTUM','WQTM'])

Fetched history for WQTM (45 weeks)

  symbol                               name  weeks   gmean     std    sharpe
0   QTUM               Defiance Quantum ETF     34  29.95%   8.82%  2.943011
1   WQTM  WisdomTree Quantum Computing Fund     34  23.14%  11.24%  1.703675

In [11]:
# Power picks
crunch(156, 52, ['NUKZ','NLR','AIPO'])

,symbol,name,weeks,gmean,std,sharpe
0,AIPO,Defiance AI & Power Infrastructure ETF,56,46.29%,4.68%,9.028519
1,NUKZ,Range Nuclear Renaissance ETF,134,53.43%,24.49%,2.018334
2,NLR,VanEck Uranium and Nuclear ETF,156,34.96%,28.26%,1.095836

In [12]:
# Defense picks
crunch(88, 52, ['ITA','PPA','XAR','4MMR.DE','DFEN.DE'])

Fetched history for ITA (261 weeks)
Fetched history for XAR (261 weeks)
Fetched history for 4MMR.DE (100 weeks)

,symbol,name,weeks,gmean,std,sharpe
0,XAR,State Street SPDR S&P Aerospace & Defense ETF,88,49.39%,15.96%,2.844496
1,ITA,iShares U.S. Aerospace & Defense ETF,88,41.68%,13.74%,2.743425
2,PPA,Invesco Aerospace & Defense ETF,88,37.58%,12.71%,2.642418
3,DFEN.DE,VanEck Defense ETF A USD Acc,88,32.88%,22.24%,1.298605
4,4MMR.DE,Global X Defence Tech UCITS ETF USD Accumulating,88,34.45%,25.78%,1.181056

In [13]:
# Crypto picks
crunch(158, 52, ['DAPP','BITQ','BTC-USD'])

,symbol,name,weeks,gmean,std,sharpe
0,BITQ,Bitwise Crypto Industry Innovators ETF,158,51.78%,40.39%,1.182935
1,DAPP,VanEck Digital Transformation ETF,158,50.17%,47.34%,0.975200
2,BTC-USD,Bitcoin USD,158,31.85%,63.92%,0.435745

In [14]:
# Financial picks
crunch(262, 52, ['EXV1.DE','ESIF.DE'])

Fetched history for EXV1.DE (261 weeks)

,symbol,name,weeks,gmean,std,sharpe
0,EXV1.DE,iShares STOXX Europe 600 Banks UCITS ETF (DE),261,32.86%,20.37%,1.416762
1,ESIF.DE,iShares MSCI Europe Financials Sector UCITS ETF,261,22.75%,14.00%,1.338957

In [10]:
# Gold
crunch(156, 52, ['GC=F','GLDM','IAUM','SGOL','BAR','AAAU','IAU','OUNZ','GLD','FGDL',
                 '4GLD.DE','GLDA.DE','PPFB.DE','8PSG.DE','XGDU.DE','PHAU.L',
                 'EURUSD=X'])

,symbol,name,weeks,gmean,std,sharpe
0,GLDA.DE,Amundi Physical Gold ETC C,156,36.99%,8.74%,3.773033
1,PPFB.DE,iShares Physical Gold ETC,156,36.99%,8.75%,3.771990
2,4GLD.DE,Xetra-Gold,156,37.09%,8.82%,3.752531
3,XGDU.DE,Xtrackers IE Physical Gold ETC,156,37.19%,9.07%,3.659259
4,8PSG.DE,Invesco Physical Gold ETC,156,38.95%,9.60%,3.640592
5,GC=F,Gold Dec 26,156,42.28%,13.88%,2.757069
6,FGDL,Franklin Responsibly Sourced Gold ETF,156,42.14%,13.84%,2.756120
7,GLDM,SPDR Gold MiniShares,156,42.14%,14.10%,2.703967
8,IAUM,iShares Gold Trust Micro,156,42.17%,14.14%,2.699476
9,BAR,GraniteShares Gold Trust,156,42.03%,14.12%,2.693346
10,AAAU,Goldman Sachs Physical Gold ETF,156,42.01%,14.11%,2.693245
11,SGOL,abrdn Physical Gold Shares ETF,156,42.02%,14.13%,2.691164
12,IAU,iShares Gold Trust,156,41.92%,14.11%,2.687146
13,OUNZ,VanEck Merk Gold Trust,156,41.91%,14.11%,2.685934
14,PHAU.L,WisdomTree Physical Gold,156,41.75%,14.06%,2.684286
15,GLD,SPDR Gold Shares,156,41.72%,14.11%,2.673745
16,EURUSD=X,EUR/USD,156,3.71%,5.39%,-0.053892

In [6]:
# Materials & Industrials
crunch(156, 52, ['XDWI.DE','WIND.AS','EXI','WMIN.DE','PICK','XDWM.DE','COPX','URNM'])

,symbol,name,weeks,gmean,std,sharpe
0,EXI,iShares Global Industrials ETF,156,21.82%,8.45%,2.107897
1,XDWI.DE,Xtrackers MSCI World Industrials UCITS ETF 1C,156,17.49%,8.91%,1.513455
2,WIND.AS,State Street SPDR MSCI World Industrials UCITS...,156,17.42%,8.88%,1.511300
3,WMIN.DE,VanEck S&P Global Mining UCITS ETF,156,32.65%,34.19%,0.838081
4,COPX,Global X Copper Miners ETF,156,39.61%,48.21%,0.738733
5,PICK,iShares MSCI Global Metals & Mining Producers ETF,156,19.95%,34.33%,0.464605
6,XDWM.DE,Xtrackers MSCI World Materials UCITS ETF 1C,156,9.66%,13.59%,0.416466
7,URNM,Sprott Uranium Miners ETF,156,14.08%,41.33%,0.243924

In [18]:
# Tech & AI picks
crunch(156, 52, ['MAGS','FNGS','SPMO','IGM','QQQ','BAI','WTAI','AGIX','CHAT','AIQ','BOTZ','ROBO','THNQ','ARKQ','LRNZ','WISE'])

Fetched history for WTAI (245 weeks)
Fetched history for AIQ (261 weeks)
Fetched history for BOTZ (261 weeks)
Fetched history for ROBO (261 weeks)
Fetched history for THNQ (261 weeks)
Fetched history for ARKQ (261 weeks)
Fetched history for LRNZ (261 weeks)
Fetched history for WISE (141 weeks)

,symbol,name,weeks,gmean,std,sharpe
0,AGIX,KraneShares Artificial Intelligence and Techno...,109,37.85%,13.57%,2.494532
1,SPMO,Invesco S&P 500 Momentum ETF,156,34.34%,13.48%,2.250923
2,AIQ,Global X Artificial Intelligence & Technology ETF,156,30.15%,12.67%,2.064168
3,QQQ,Invesco QQQ Trust,156,23.88%,9.88%,2.011875
4,IGM,iShares Expanded Tech Sector ETF,156,31.36%,14.50%,1.886557
5,ARKQ,ARK Autonomous Technology & Robotics ETF,156,48.97%,23.92%,1.879592
6,FNGS,MicroSectors FANG+ ETN,156,31.25%,14.90%,1.829384
7,MAGS,Roundhill Magnificent Seven ETF,156,34.07%,16.82%,1.787517
8,BAI,iShares A.I. Innovation and Tech Active ETF,95,49.24%,27.48%,1.646416
9,THNQ,Robo Global Artificial Intelligence ETF,156,31.10%,17.66%,1.534878
10,CHAT,Roundhill Generative AI & Technology ETF,156,47.91%,33.81%,1.298741
11,WISE,Themes Generative Artificial Intelligence ETF,141,21.03%,17.81%,0.956021
12,WTAI,WisdomTree Artificial Intelligence and Innovat...,156,30.66%,28.58%,0.932728
13,LRNZ,"TrueShares Technology, AI and Deep Learning ETF",156,16.92%,14.55%,0.888469
14,BOTZ,Global X Robotics & Artificial Intelligence ETF,156,13.36%,12.40%,0.754752
15,ROBO,Robo-Stox Global Robotics and Automation Index...,156,17.24%,18.34%,0.721927