In [ ]:
import pandas as pd
from scipy.stats import gmean
from yfetch import get_stock_history

symbol_map = {} # symbol : full name
symbol_types = {} # symbol : ETF/stock

sp500_stocks = pd.read_csv('data/sp500_stocks.csv')
symbol_map.update(sp500_stocks.set_index('Symbol')['Security'].to_dict())
symbol_types.update({symbol: 'stock' for symbol in sp500_stocks['Symbol']})

top_etfs = pd.read_csv('data/top-etfs.csv')
symbol_map.update(top_etfs.set_index('Symbol')['ETF Name'].to_dict())
symbol_types.update({symbol: 'ETF' for symbol in top_etfs['Symbol']})

# yf uses '-' instead of '.'
symbol_map = {k.replace('.', '-'): v for k, v in symbol_map.items()} 
symbol_types = {k.replace('.', '-'): v for k, v in symbol_types.items()}

ucits = {
  'EHF1.DE': 'Amundi MSCI Europe High Dividend Factor UCITS',
  'EHDV.DE': 'Invesco EURO STOXX High Dividend Low Volatility UCITS',
  'QDVE.DE': 'iShares S&P 500 Information Technology Sector UCITS',
  'SPPY.DE': 'SPDR S&P 500 Leaders UCITS',
  'SPPE.DE': 'SPDR S&P 500 UCITS',
  'NQSE.DE': 'iShares VII PLC - iShares NASDAQ 100 UCITS',
  'EXV1.DE': 'iShares STOXX Europe 600 Banks UCITS',
  'VDIV.DE': 'VanEck Morningstar Developed Markets Dividend Leaders UCITS', # not on Revolut
  'SPYZ.DE': 'SPDR MSCI Europe Financials UCITS',
  'EXH2.DE': 'iShares STOXX Europe 600 Financial Services UCITS',
  'ESIF.DE': 'iShares MSCI Europe Financials Sector UCITS',
  'SC02.DE': 'Invesco STOXX Europe 600 Optimised Financial Services UCITS',
}
symbol_map.update(ucits)
symbol_types.update({symbol: 'UCITS' for symbol in ucits.keys()})

crypto = {
  'BTC-USD': 'Bitcoin',
  'ETH-USD': 'Ethereum',
  'SOL-USD': 'Solana',
}

symbol_map.update(crypto)
symbol_types.update({symbol: 'crypto' for symbol in crypto.keys()})

symbol_map['GC=F'] = 'Gold'
symbol_types['GC=F'] = 'commodity'

In [8]:
hm = {}
for symbol, description in symbol_map.items():
  history = get_stock_history(symbol, interval='1wk', cache_days=100)
  print(f'[{len(hm)}/{len(symbol_map)}] {len(history)}w {symbol} {symbol_types[symbol]} ({description})')
  hm[symbol] = history

[0/1520] 261w MMM stock (3M)
[1/1520] 261w AOS stock (A. O. Smith)
[2/1520] 261w ABT stock (Abbott Laboratories)
[3/1520] 261w ABBV stock (AbbVie)
[4/1520] 261w ACN stock (Accenture)
[5/1520] 261w ADBE stock (Adobe Inc.)
[6/1520] 261w AMD stock (Advanced Micro Devices)
[7/1520] 261w AES stock (AES Corporation)
[8/1520] 261w AFL stock (Aflac)
[9/1520] 261w A stock (Agilent Technologies)
[10/1520] 261w APD stock (Air Products)
[11/1520] 253w ABNB stock (Airbnb)
[12/1520] 261w AKAM stock (Akamai Technologies)
[13/1520] 261w ALB stock (Albemarle Corporation)
[14/1520] 261w ARE stock (Alexandria Real Estate Equities)
[15/1520] 261w ALGN stock (Align Technology)
[16/1520] 261w ALLE stock (Allegion)
[17/1520] 261w LNT stock (Alliant Energy)
[18/1520] 261w ALL stock (Allstate)
[19/1520] 261w GOOGL stock (Alphabet Inc. (Class A))
[20/1520] 261w GOOG stock (Alphabet Inc. (Class C))
[21/1520] 261w MO stock (Altria)
[22/1520] 261w AMZN stock (Amazon)
[23/1520] 261w AMCR stock (Amcor)
[24/1520] 261w AEE stock (Ameren)
[25/1520] 261w AEP stock (American Electric Power)
[26/1520] 261w AXP stock (American Express)
[27/1520] 261w AIG stock (American International Group)
[28/1520] 261w AMT stock (American Tower)
[29/1520] 261w AWK stock (American Water Works)
[30/1520] 261w AMP stock (Ameriprise Financial)
[31/1520] 261w AME stock (Ametek)
[32/1520] 261w AMGN stock (Amgen)
[33/1520] 261w APH stock (Amphenol)
[34/1520] 261w ADI stock (Analog Devices)
[35/1520] 261w AON stock (Aon plc)
[36/1520] 261w APA stock (APA Corporation)
[37/1520] 261w APO stock (Apollo Global Management)
[38/1520] 261w AAPL stock (Apple Inc.)
[39/1520] 261w AMAT stock (Applied Materials)
[40/1520] 235w APP stock (AppLovin)
[41/1520] 261w APTV stock (Aptiv)
[42/1520] 261w ACGL stock (Arch Capital Group)
[43/1520] 261w ADM stock (Archer Daniels Midland)
[44/1520] 261w ANET stock (Arista Networks)
[45/1520] 261w AJG stock (Arthur J. Gallagher & Co.)
[46/1520] 261w AIZ stock (Assurant)
[47/1520] 261w T stock (AT&T)
[48/1520] 261w ATO stock (Atmos Energy)
[49/1520] 261w ADSK stock (Autodesk)
[50/1520] 261w ADP stock (Automatic Data Processing)
[51/1520] 261w AZO stock (AutoZone)
[52/1520] 261w AVB stock (AvalonBay Communities)
[53/1520] 261w AVY stock (Avery Dennison)
[54/1520] 261w AXON stock (Axon Enterprise)
[55/1520] 261w BKR stock (Baker Hughes)
[56/1520] 261w BALL stock (Ball Corporation)
[57/1520] 261w BAC stock (Bank of America)
[58/1520] 261w BAX stock (Baxter International)
[59/1520] 261w BDX stock (Becton Dickinson)
[60/1520] 261w BRK-B stock (Berkshire Hathaway)
[61/1520] 261w BBY stock (Best Buy)
[62/1520] 261w TECH stock (Bio-Techne)
[63/1520] 261w BIIB stock (Biogen)
[64/1520] 261w BLK stock (BlackRock)
[65/1520] 261w BX stock (Blackstone Inc.)
[66/1520] 261w XYZ stock (Block, Inc.)
[67/1520] 261w BK stock (BNY Mellon)
[68/1520] 261w BA stock (Boeing)
[69/1520] 261w BKNG stock (Booking Holdings)
[70/1520] 261w BSX stock (Boston Scientific)
[71/1520] 261w BMY stock (Bristol Myers Squibb)
[72/1520] 261w AVGO stock (Broadcom)
[73/1520] 261w BR stock (Broadridge Financial Solutions)
[74/1520] 261w BRO stock (Brown & Brown)
[75/1520] 261w BF-B stock (Brown–Forman)
[76/1520] 261w BLDR stock (Builders FirstSource)
[77/1520] 261w BG stock (Bunge Global)
[78/1520] 261w BXP stock (BXP, Inc.)
[79/1520] 261w CHRW stock (C.H. Robinson)
[80/1520] 261w CDNS stock (Cadence Design Systems)
[81/1520] 261w CPT stock (Camden Property Trust)
[82/1520] 261w CPB stock (Campbell's Company (The))
[83/1520] 261w COF stock (Capital One)
[84/1520] 261w CAH stock (Cardinal Health)
[85/1520] 261w KMX stock (CarMax)
[86/1520] 261w CCL stock (Carnival)
[87/1520] 261w CARR stock (Carrier Global)
[88/1520] 261w CAT stock (Caterpillar Inc.)
[89/1520] 261w CBOE stock (Cboe Global Markets)
[90/1520] 261w CBRE stock (CBRE Group)
[91/1520] 261w CDW stock (CDW Corporation)
[92/1520] 261w COR stock (Cencora)
[93/1520] 261w CNC stock (Centene Corporation)
[94/1520] 261w CNP stock (CenterPoint Energy)
[95/1520] 261w CF stock (CF Industries)
[96/1520] 261w CRL stock (Charles River Laboratories)
[97/1520] 261w SCHW stock (Charles Schwab Corporation)
[98/1520] 261w CHTR stock (Charter Communications)
[99/1520] 261w CVX stock (Chevron Corporation)
[100/1520] 261w CMG stock (Chipotle Mexican Grill)
[101/1520] 261w CB stock (Chubb Limited)
[102/1520] 261w CHD stock (Church & Dwight)
[103/1520] 261w CI stock (Cigna)
[104/1520] 261w CINF stock (Cincinnati Financial)
[105/1520] 261w CTAS stock (Cintas)
[106/1520] 261w CSCO stock (Cisco)
[107/1520] 261w C stock (Citigroup)
[108/1520] 261w CFG stock (Citizens Financial Group)
[109/1520] 261w CLX stock (Clorox)
[110/1520] 261w CME stock (CME Group)
[111/1520] 261w CMS stock (CMS Energy)
[112/1520] 261w KO stock (Coca-Cola Company (The))
[113/1520] 261w CTSH stock (Cognizant)
[114/1520] 235w COIN stock (Coinbase)
[115/1520] 261w CL stock (Colgate-Palmolive)
[116/1520] 261w CMCSA stock (Comcast)
[117/1520] 261w CAG stock (Conagra Brands)
[118/1520] 261w COP stock (ConocoPhillips)
[119/1520] 261w ED stock (Consolidated Edison)
[120/1520] 261w STZ stock (Constellation Brands)
[121/1520] 195w CEG stock (Constellation Energy)
[122/1520] 261w COO stock (Cooper Companies (The))
[123/1520] 261w CPRT stock (Copart)
[124/1520] 261w GLW stock (Corning Inc.)
[125/1520] 261w CPAY stock (Corpay)
[126/1520] 261w CTVA stock (Corteva)
[127/1520] 261w CSGP stock (CoStar Group)
[128/1520] 261w COST stock (Costco)
[129/1520] 261w CTRA stock (Coterra)
[130/1520] 261w CRWD stock (CrowdStrike)
[131/1520] 261w CCI stock (Crown Castle)
[132/1520] 261w CSX stock (CSX Corporation)
[133/1520] 261w CMI stock (Cummins)
[134/1520] 261w CVS stock (CVS Health)
[135/1520] 261w DHR stock (Danaher Corporation)
[136/1520] 261w DRI stock (Darden Restaurants)
[137/1520] 261w DDOG stock (Datadog)
[138/1520] 261w DVA stock (DaVita)
[139/1520] 261w DAY stock (Dayforce)
[140/1520] 261w DECK stock (Deckers Brands)
[141/1520] 261w DE stock (Deere & Company)
[142/1520] 261w DELL stock (Dell Technologies)
[143/1520] 261w DAL stock (Delta Air Lines)
[144/1520] 261w DVN stock (Devon Energy)
[145/1520] 261w DXCM stock (Dexcom)
[146/1520] 261w FANG stock (Diamondback Energy)
[147/1520] 261w DLR stock (Digital Realty)
[148/1520] 261w DG stock (Dollar General)
[149/1520] 261w DLTR stock (Dollar Tree)
[150/1520] 261w D stock (Dominion Energy)
[151/1520] 261w DPZ stock (Domino's)
[152/1520] 253w DASH stock (DoorDash)
[153/1520] 261w DOV stock (Dover Corporation)
[154/1520] 261w DOW stock (Dow Inc.)
[155/1520] 261w DHI stock (D. R. Horton)
[156/1520] 261w DTE stock (DTE Energy)
[157/1520] 261w DUK stock (Duke Energy)
[158/1520] 261w DD stock (DuPont)
[159/1520] 261w EMN stock (Eastman Chemical Company)
[160/1520] 261w ETN stock (Eaton Corporation)
[161/1520] 261w EBAY stock (eBay Inc.)
[162/1520] 261w ECL stock (Ecolab)
[163/1520] 261w EIX stock (Edison International)
[164/1520] 261w EW stock (Edwards Lifesciences)
[165/1520] 261w EA stock (Electronic Arts)
[166/1520] 261w ELV stock (Elevance Health)
[167/1520] 261w EME stock (Emcor)
[168/1520] 261w EMR stock (Emerson Electric)
[169/1520] 261w ETR stock (Entergy)
[170/1520] 261w EOG stock (EOG Resources)
[171/1520] 261w EPAM stock (EPAM Systems)
[172/1520] 261w EQT stock (EQT Corporation)
[173/1520] 261w EFX stock (Equifax)
[174/1520] 261w EQIX stock (Equinix)
[175/1520] 261w EQR stock (Equity Residential)
[176/1520] 261w ERIE stock (Erie Indemnity)
[177/1520] 261w ESS stock (Essex Property Trust)
[178/1520] 261w EL stock (Estée Lauder Companies (The))
[179/1520] 261w EG stock (Everest Group)
[180/1520] 261w EVRG stock (Evergy)
[181/1520] 261w ES stock (Eversource Energy)
[182/1520] 261w EXC stock (Exelon)
[183/1520] 244w EXE stock (Expand Energy)
[184/1520] 261w EXPE stock (Expedia Group)
[185/1520] 261w EXPD stock (Expeditors International)
[186/1520] 261w EXR stock (Extra Space Storage)
[187/1520] 261w XOM stock (ExxonMobil)
[188/1520] 261w FFIV stock (F5, Inc.)
[189/1520] 261w FDS stock (FactSet)
[190/1520] 261w FICO stock (Fair Isaac)
[191/1520] 261w FAST stock (Fastenal)
[192/1520] 261w FRT stock (Federal Realty Investment Trust)
[193/1520] 261w FDX stock (FedEx)
[194/1520] 261w FIS stock (Fidelity National Information Services)
[195/1520] 261w FITB stock (Fifth Third Bancorp)
[196/1520] 261w FSLR stock (First Solar)
[197/1520] 261w FE stock (FirstEnergy)
[198/1520] 261w FI stock (Fiserv)
[199/1520] 261w F stock (Ford Motor Company)
[200/1520] 261w FTNT stock (Fortinet)
[201/1520] 261w FTV stock (Fortive)
[202/1520] 261w FOXA stock (Fox Corporation (Class A))
[203/1520] 261w FOX stock (Fox Corporation (Class B))
[204/1520] 261w BEN stock (Franklin Resources)
[205/1520] 261w FCX stock (Freeport-McMoRan)
[206/1520] 261w GRMN stock (Garmin)
[207/1520] 261w IT stock (Gartner)
[208/1520] 261w GE stock (GE Aerospace)
[209/1520] 148w GEHC stock (GE HealthCare)
[210/1520] 81w GEV stock (GE Vernova)
[211/1520] 261w GEN stock (Gen Digital)
[212/1520] 261w GNRC stock (Generac)
[213/1520] 261w GD stock (General Dynamics)
[214/1520] 261w GIS stock (General Mills)
[215/1520] 261w GM stock (General Motors)
[216/1520] 261w GPC stock (Genuine Parts Company)
[217/1520] 261w GILD stock (Gilead Sciences)
[218/1520] 261w GPN stock (Global Payments)
[219/1520] 261w GL stock (Globe Life)
[220/1520] 261w GDDY stock (GoDaddy)
[221/1520] 261w GS stock (Goldman Sachs)
[222/1520] 261w HAL stock (Halliburton)
[223/1520] 261w HIG stock (Hartford (The))
[224/1520] 261w HAS stock (Hasbro)
[225/1520] 261w HCA stock (HCA Healthcare)
[226/1520] 261w DOC stock (Healthpeak Properties)
[227/1520] 261w HSIC stock (Henry Schein)
[228/1520] 261w HSY stock (Hershey Company (The))
[229/1520] 261w HPE stock (Hewlett Packard Enterprise)
[230/1520] 261w HLT stock (Hilton Worldwide)
[231/1520] 261w HOLX stock (Hologic)
[232/1520] 261w HD stock (Home Depot (The))
[233/1520] 261w HON stock (Honeywell)
[234/1520] 261w HRL stock (Hormel Foods)
[235/1520] 261w HST stock (Host Hotels & Resorts)
[236/1520] 261w HWM stock (Howmet Aerospace)
[237/1520] 261w HPQ stock (HP Inc.)
[238/1520] 261w HUBB stock (Hubbell Incorporated)
[239/1520] 261w HUM stock (Humana)
[240/1520] 261w HBAN stock (Huntington Bancshares)
[241/1520] 261w HII stock (Huntington Ingalls Industries)
[242/1520] 261w IBM stock (IBM)
[243/1520] 261w IEX stock (IDEX Corporation)
[244/1520] 261w IDXX stock (Idexx Laboratories)
[245/1520] 261w ITW stock (Illinois Tool Works)
[246/1520] 261w INCY stock (Incyte)
[247/1520] 261w IR stock (Ingersoll Rand)
[248/1520] 261w PODD stock (Insulet Corporation)
[249/1520] 261w INTC stock (Intel)
[250/1520] 261w IBKR stock (Interactive Brokers)
[251/1520] 261w ICE stock (Intercontinental Exchange)
[252/1520] 261w IFF stock (International Flavors & Fragrances)
[253/1520] 261w IP stock (International Paper)
[254/1520] 261w IPG stock (Interpublic Group of Companies (The))
[255/1520] 261w INTU stock (Intuit)
[256/1520] 261w ISRG stock (Intuitive Surgical)
[257/1520] 261w IVZ stock (Invesco)
[258/1520] 261w INVH stock (Invitation Homes)
[259/1520] 261w IQV stock (IQVIA)
[260/1520] 261w IRM stock (Iron Mountain)
[261/1520] 261w JBHT stock (J.B. Hunt)
[262/1520] 261w JBL stock (Jabil)
[263/1520] 261w JKHY stock (Jack Henry & Associates)
[264/1520] 261w J stock (Jacobs Solutions)
[265/1520] 261w JNJ stock (Johnson & Johnson)
[266/1520] 261w JCI stock (Johnson Controls)
[267/1520] 261w JPM stock (JPMorgan Chase)
[268/1520] 261w K stock (Kellanova)
[269/1520] 128w KVUE stock (Kenvue)
[270/1520] 261w KDP stock (Keurig Dr Pepper)
[271/1520] 261w KEY stock (KeyCorp)
[272/1520] 261w KEYS stock (Keysight Technologies)
[273/1520] 261w KMB stock (Kimberly-Clark)
[274/1520] 261w KIM stock (Kimco Realty)
[275/1520] 261w KMI stock (Kinder Morgan)
[276/1520] 261w KKR stock (KKR & Co.)
[277/1520] 261w KLAC stock (KLA Corporation)
[278/1520] 261w KHC stock (Kraft Heinz)
[279/1520] 261w KR stock (Kroger)
[280/1520] 261w LHX stock (L3Harris)
[281/1520] 261w LH stock (Labcorp)
[282/1520] 261w LRCX stock (Lam Research)
[283/1520] 261w LW stock (Lamb Weston)
[284/1520] 261w LVS stock (Las Vegas Sands)
[285/1520] 261w LDOS stock (Leidos)
[286/1520] 261w LEN stock (Lennar)
[287/1520] 261w LII stock (Lennox International)
[288/1520] 261w LLY stock (Lilly (Eli))
[289/1520] 261w LIN stock (Linde plc)
[290/1520] 261w LYV stock (Live Nation Entertainment)
[291/1520] 261w LKQ stock (LKQ Corporation)
[292/1520] 261w LMT stock (Lockheed Martin)
[293/1520] 261w L stock (Loews Corporation)
[294/1520] 261w LOW stock (Lowe's)
[295/1520] 261w LULU stock (Lululemon Athletica)
[296/1520] 261w LYB stock (LyondellBasell)
[297/1520] 261w MTB stock (M&T Bank)
[298/1520] 261w MPC stock (Marathon Petroleum)
[299/1520] 261w MAR stock (Marriott International)
[300/1520] 261w MMC stock (Marsh McLennan)
[301/1520] 261w MLM stock (Martin Marietta Materials)
[302/1520] 261w MAS stock (Masco)
[303/1520] 261w MA stock (Mastercard)
[304/1520] 261w MTCH stock (Match Group)
[305/1520] 261w MKC stock (McCormick & Company)
[306/1520] 261w MCD stock (McDonald's)
[307/1520] 261w MCK stock (McKesson Corporation)
[308/1520] 261w MDT stock (Medtronic)
[309/1520] 261w MRK stock (Merck & Co.)
[310/1520] 261w META stock (Meta Platforms)
[311/1520] 261w MET stock (MetLife)
[312/1520] 261w MTD stock (Mettler Toledo)
[313/1520] 261w MGM stock (MGM Resorts)
[314/1520] 261w MCHP stock (Microchip Technology)
[315/1520] 261w MU stock (Micron Technology)
[316/1520] 261w MSFT stock (Microsoft)
[317/1520] 261w MAA stock (Mid-America Apartment Communities)
[318/1520] 261w MRNA stock (Moderna)
[319/1520] 261w MHK stock (Mohawk Industries)
[320/1520] 261w MOH stock (Molina Healthcare)
[321/1520] 261w TAP stock (Molson Coors Beverage Company)
[322/1520] 261w MDLZ stock (Mondelez International)
[323/1520] 261w MPWR stock (Monolithic Power Systems)
[324/1520] 261w MNST stock (Monster Beverage)
[325/1520] 261w MCO stock (Moody's Corporation)
[326/1520] 261w MS stock (Morgan Stanley)
[327/1520] 261w MOS stock (Mosaic Company (The))
[328/1520] 261w MSI stock (Motorola Solutions)
[329/1520] 261w MSCI stock (MSCI Inc.)
[330/1520] 261w NDAQ stock (Nasdaq, Inc.)
[331/1520] 261w NTAP stock (NetApp)
[332/1520] 261w NFLX stock (Netflix)
[333/1520] 261w NEM stock (Newmont)
[334/1520] 261w NWSA stock (News Corp (Class A))
[335/1520] 261w NWS stock (News Corp (Class B))
[336/1520] 261w NEE stock (NextEra Energy)
[337/1520] 261w NKE stock (Nike, Inc.)
[338/1520] 261w NI stock (NiSource)
[339/1520] 261w NDSN stock (Nordson Corporation)
[340/1520] 261w NSC stock (Norfolk Southern)
[341/1520] 261w NTRS stock (Northern Trust)
[342/1520] 261w NOC stock (Northrop Grumman)
[343/1520] 261w NCLH stock (Norwegian Cruise Line Holdings)
[344/1520] 261w NRG stock (NRG Energy)
[345/1520] 261w NUE stock (Nucor)
[346/1520] 261w NVDA stock (Nvidia)
[347/1520] 261w NVR stock (NVR, Inc.)
[348/1520] 261w NXPI stock (NXP Semiconductors)
[349/1520] 261w ORLY stock (O’Reilly Automotive)
[350/1520] 261w OXY stock (Occidental Petroleum)
[351/1520] 261w ODFL stock (Old Dominion)
[352/1520] 261w OMC stock (Omnicom Group)
[353/1520] 261w ON stock (ON Semiconductor)
[354/1520] 261w OKE stock (Oneok)
[355/1520] 261w ORCL stock (Oracle Corporation)
[356/1520] 261w OTIS stock (Otis Worldwide)
[357/1520] 261w PCAR stock (Paccar)
[358/1520] 261w PKG stock (Packaging Corporation of America)
[359/1520] 261w PLTR stock (Palantir Technologies)
[360/1520] 261w PANW stock (Palo Alto Networks)
[361/1520] 261w PSKY stock (Paramount Skydance Corporation)
[362/1520] 261w PH stock (Parker Hannifin)
[363/1520] 261w PAYX stock (Paychex)
[364/1520] 261w PAYC stock (Paycom)
[365/1520] 261w PYPL stock (PayPal)
[366/1520] 261w PNR stock (Pentair)
[367/1520] 261w PEP stock (PepsiCo)
[368/1520] 261w PFE stock (Pfizer)
[369/1520] 261w PCG stock (PG&E Corporation)
[370/1520] 261w PM stock (Philip Morris International)
[371/1520] 261w PSX stock (Phillips 66)
[372/1520] 261w PNW stock (Pinnacle West Capital)
[373/1520] 261w PNC stock (PNC Financial Services)
[374/1520] 261w POOL stock (Pool Corporation)
[375/1520] 261w PPG stock (PPG Industries)
[376/1520] 261w PPL stock (PPL Corporation)
[377/1520] 261w PFG stock (Principal Financial Group)
[378/1520] 261w PG stock (Procter & Gamble)
[379/1520] 261w PGR stock (Progressive Corporation)
[380/1520] 261w PLD stock (Prologis)
[381/1520] 261w PRU stock (Prudential Financial)
[382/1520] 261w PEG stock (Public Service Enterprise Group)
[383/1520] 261w PTC stock (PTC Inc.)
[384/1520] 261w PSA stock (Public Storage)
[385/1520] 261w PHM stock (PulteGroup)
[386/1520] 261w PWR stock (Quanta Services)
[387/1520] 261w QCOM stock (Qualcomm)
[388/1520] 261w DGX stock (Quest Diagnostics)
[389/1520] 261w RL stock (Ralph Lauren Corporation)
[390/1520] 261w RJF stock (Raymond James Financial)
[391/1520] 261w RTX stock (RTX Corporation)
[392/1520] 261w O stock (Realty Income)
[393/1520] 261w REG stock (Regency Centers)
[394/1520] 261w REGN stock (Regeneron Pharmaceuticals)
[395/1520] 261w RF stock (Regions Financial Corporation)
[396/1520] 261w RSG stock (Republic Services)
[397/1520] 261w RMD stock (ResMed)
[398/1520] 261w RVTY stock (Revvity)
[399/1520] 220w HOOD stock (Robinhood Markets)
[400/1520] 261w ROK stock (Rockwell Automation)
[401/1520] 261w ROL stock (Rollins, Inc.)
[402/1520] 261w ROP stock (Roper Technologies)
[403/1520] 261w ROST stock (Ross Stores)
[404/1520] 261w RCL stock (Royal Caribbean Group)
[405/1520] 261w SPGI stock (S&P Global)
[406/1520] 261w CRM stock (Salesforce)
[407/1520] 261w SBAC stock (SBA Communications)
[408/1520] 261w SLB stock (Schlumberger)
[409/1520] 261w STX stock (Seagate Technology)
[410/1520] 261w SRE stock (Sempra)
[411/1520] 261w NOW stock (ServiceNow)
[412/1520] 261w SHW stock (Sherwin-Williams)
[413/1520] 261w SPG stock (Simon Property Group)
[414/1520] 261w SWKS stock (Skyworks Solutions)
[415/1520] 261w SJM stock (J.M. Smucker Company (The))
[416/1520] 261w SW stock (Smurfit Westrock)
[417/1520] 261w SNA stock (Snap-on)
[418/1520] 81w SOLV stock (Solventum)
[419/1520] 261w SO stock (Southern Company)
[420/1520] 261w LUV stock (Southwest Airlines)
[421/1520] 261w SWK stock (Stanley Black & Decker)
[422/1520] 261w SBUX stock (Starbucks)
[423/1520] 261w STT stock (State Street Corporation)
[424/1520] 261w STLD stock (Steel Dynamics)
[425/1520] 261w STE stock (Steris)
[426/1520] 261w SYK stock (Stryker Corporation)
[427/1520] 261w SMCI stock (Supermicro)
[428/1520] 261w SYF stock (Synchrony Financial)
[429/1520] 261w SNPS stock (Synopsys)
[430/1520] 261w SYY stock (Sysco)
[431/1520] 261w TMUS stock (T-Mobile US)
[432/1520] 261w TROW stock (T. Rowe Price)
[433/1520] 261w TTWO stock (Take-Two Interactive)
[434/1520] 261w TPR stock (Tapestry, Inc.)
[435/1520] 261w TRGP stock (Targa Resources)
[436/1520] 261w TGT stock (Target Corporation)
[437/1520] 261w TEL stock (TE Connectivity)
[438/1520] 261w TDY stock (Teledyne Technologies)
[439/1520] 261w TER stock (Teradyne)
[440/1520] 261w TSLA stock (Tesla, Inc.)
[441/1520] 261w TXN stock (Texas Instruments)
[442/1520] 261w TPL stock (Texas Pacific Land Corporation)
[443/1520] 261w TXT stock (Textron)
[444/1520] 261w TMO stock (Thermo Fisher Scientific)
[445/1520] 261w TJX stock (TJX Companies)
[446/1520] 261w TKO stock (TKO Group Holdings)
[447/1520] 261w TTD stock (Trade Desk (The))
[448/1520] 261w TSCO stock (Tractor Supply)
[449/1520] 261w TT stock (Trane Technologies)
[450/1520] 261w TDG stock (TransDigm Group)
[451/1520] 261w TRV stock (Travelers Companies (The))
[452/1520] 261w TRMB stock (Trimble Inc.)
[453/1520] 261w TFC stock (Truist Financial)
[454/1520] 261w TYL stock (Tyler Technologies)
[455/1520] 261w TSN stock (Tyson Foods)
[456/1520] 261w USB stock (U.S. Bancorp)
[457/1520] 261w UBER stock (Uber)
[458/1520] 261w UDR stock (UDR, Inc.)
[459/1520] 261w ULTA stock (Ulta Beauty)
[460/1520] 261w UNP stock (Union Pacific Corporation)
[461/1520] 261w UAL stock (United Airlines Holdings)
[462/1520] 261w UPS stock (United Parcel Service)

In [9]:
def run(window=52, history_len=261):
  rows = []

  for symbol, history in hm.items():
    if len(history) < history_len:
      continue
    history = history.tail(history_len)
    sma = history.Close.rolling(window=13).mean().dropna()
    cagr = (sma.iloc[-1] / sma.iloc[0]) ** (1 / (len(sma) / 52)) - 1
    changes = history.Close.pct_change(periods=window).dropna()
    median = changes.median()
    gmean_change = gmean(1 + changes) - 1  # Geometric mean of changes
    std = changes.std()
    fields = {
        'symbol': symbol,
        'description': symbol_map[symbol],
        'type': symbol_types[symbol],
        'weeks': len(history),
        'cagr': cagr,
        'median change': median,
        'gmean change': gmean_change,
        'std': std,
        'gmean/std': std and gmean_change / std,
        'median/std': std and median / std
    }
    rows.append(fields)

  df = pd.DataFrame(rows).sort_values(by='gmean/std', ascending=False)
  df.to_csv(f'data/top-stox-{window}w-over-{history_len}w.csv', index=False)

  for col in ['cagr', 'gmean change', 'median change', 'std']:
      df[col] = df[col].map('{:.2%}'.format)
  display(df)

In [10]:
run(13, 104) # 1Q over 2y

,symbol,description,type,weeks,cagr,median change,gmean change,std,gmean/std,median/std
756,BOXX,Alpha Architect 1-3 Month Box ETF,ETF,104,4.82%,1.23%,1.20%,0.12%,10.202145,10.454750
925,TBLL,Invesco Short Term Treasury ETF,ETF,104,4.76%,1.16%,1.18%,0.16%,7.317370,7.201090
767,TBIL,US Treasury 3 Month Bill ETF,ETF,104,4.75%,1.23%,1.18%,0.17%,7.108304,7.379674
541,SGOV,iShares 0-3 Month Treasury Bond ETF,ETF,104,4.85%,1.28%,1.21%,0.19%,6.333635,6.731189
534,BIL,SPDR Bloomberg 1-3 Month T-Bill ETF,ETF,104,4.77%,1.26%,1.19%,0.19%,6.262139,6.647938
...,...,...,...,...,...,...,...,...,...,...
460,UPS,United Parcel Service,stock,104,-22.62%,-6.21%,-6.28%,8.20%,-0.765041,-0.757503
1448,SDS,ProShares UltraShort S&P500,ETF,104,-31.34%,-9.24%,-9.02%,11.48%,-0.786039,-0.805445
75,BF-B,Brown–Forman,stock,104,-30.41%,-9.01%,-8.77%,11.07%,-0.792238,-0.814713
1409,SPXU,ProShares UltraPro Short S&P500,ETF,104,-46.57%,-14.51%,-14.56%,16.29%,-0.893839,-0.891005
919,SQQQ,ProShares UltraPro Short QQQ,ETF,104,-55.62%,-18.96%,-18.44%,20.16%,-0.914815,-0.940361

In [11]:
run(26, 104) # 6mo over 2y

,symbol,description,type,weeks,cagr,median change,gmean change,std,gmean/std,median/std
756,BOXX,Alpha Architect 1-3 Month Box ETF,ETF,104,4.82%,2.50%,2.42%,0.20%,12.323213,12.765025
731,FTSM,First Trust Enhanced Short Maturity ETF,ETF,104,5.09%,2.46%,2.52%,0.27%,9.511040,9.282576
925,TBLL,Invesco Short Term Treasury ETF,ETF,104,4.76%,2.45%,2.39%,0.26%,9.067332,9.321148
767,TBIL,US Treasury 3 Month Bill ETF,ETF,104,4.75%,2.42%,2.37%,0.27%,8.860235,9.045541
759,ICSH,iShares Ultra Short-Term Bond Active ETF,ETF,104,5.39%,2.60%,2.67%,0.30%,8.815286,8.605891
...,...,...,...,...,...,...,...,...,...,...
1409,SPXU,ProShares UltraPro Short S&P500,ETF,104,-46.57%,-24.31%,-23.51%,16.26%,-1.445448,-1.495002
221,HAL,Halliburton,stock,104,-23.61%,-14.82%,-15.33%,10.34%,-1.482199,-1.433035
407,SLB,Schlumberger,stock,104,-19.64%,-11.32%,-11.53%,6.69%,-1.722043,-1.691398
919,SQQQ,ProShares UltraPro Short QQQ,ETF,104,-55.62%,-30.37%,-30.15%,16.59%,-1.816922,-1.830222
75,BF-B,Brown–Forman,stock,104,-30.41%,-19.54%,-17.95%,9.79%,-1.833952,-1.996503

In [12]:
run(52, 261) # 1y over 5y

,symbol,description,type,weeks,cagr,median change,gmean change,std,gmean/std,median/std
43,AJG,Arthur J. Gallagher & Co.,stock,261,22.62%,25.11%,24.72%,10.73%,2.304338,2.341462
90,COR,Cencora,stock,261,28.01%,27.94%,26.98%,11.71%,2.304021,2.386274
1308,VDIV.DE,VanEck Morningstar Developed Markets Dividend ...,ETF,261,18.11%,17.35%,16.71%,7.46%,2.240304,2.326782
340,ORLY,O’Reilly Automotive,stock,261,28.90%,26.93%,27.21%,12.21%,2.227937,2.205035
377,PWR,Quanta Services,stock,261,44.54%,41.19%,40.38%,19.17%,2.106456,2.148440
...,...,...,...,...,...,...,...,...,...,...
1115,ARKG,ARK Genomic Revolution ETF,ETF,261,-21.50%,-18.80%,-26.95%,22.07%,-1.221095,-0.851872
863,SQQQ,ProShares UltraPro Short QQQ,ETF,261,-47.80%,-50.50%,-43.54%,35.44%,-1.228508,-1.425072
295,MTCH,Match Group,stock,261,-24.19%,-21.43%,-31.02%,25.15%,-1.233667,-0.852115
1262,SPXU,ProShares UltraPro Short S&P500,ETF,261,-37.86%,-38.39%,-32.96%,24.00%,-1.373124,-1.599427
762,TMF,Direxion Daily 20+ Year Treasury Bull 3X Shares,ETF,261,-35.49%,-33.47%,-36.96%,21.24%,-1.739760,-1.575413